from langfuse import observe, Langfuse
from langfuse.openai import OpenAI
from src.models import ContractChangeOutput

# Langfuse singleton client for dynamic span updates
langfuse = Langfuse()


class ExtractionAgent:
    """
    Agent responsible for extracting structured change data using OpenAI Structured Outputs.
    Compares the original contract and the amendment with help from the alignment map
    and outputs a structured ContractChangeOutput Pydantic object.
    """

    def __init__(self, openai_client: OpenAI = None):
        self.client = openai_client or OpenAI()

    @observe(as_type="span", name="extraction_agent")
    def extract_changes(
        self,
        original_text: str,
        amendment_text: str,
        alignment_map: str,
    ) -> ContractChangeOutput:
        """
        Extracts structural changes between the original and amendment contract texts.
        
        Args:
            original_text: Transcribed text of the original contract.
            amendment_text: Transcribed text of the amendment.
            alignment_map: Structural alignment map generated by ContextualizationAgent.
            
        Returns:
            A ContractChangeOutput object containing structured fields of the changes.
        """
        # Set explicit input (avoid leaking all function args)
        langfuse.update_current_span(
            input={
                "original_text_length": len(original_text),
                "amendment_text_length": len(amendment_text),
                "alignment_map_length": len(alignment_map),
            }
        )

        system_prompt = (
            "You are an expert contract parser. Your task is to extract the exact list of modified/added/deleted "
            "clauses, the main topics touched by the amendment, and a detailed summary of the changes.\n"
            "Rely on the provided Original Contract, Amendment, and the Contextual Alignment Map.\n"
            "You must strictly adhere to the requested schema output."
        )

        user_content = (
            f"### ORIGINAL CONTRACT:\n{original_text}\n\n"
            f"### AMENDMENT CONTRACT:\n{amendment_text}\n\n"
            f"### CONTEXTUAL ALIGNMENT MAP:\n{alignment_map}\n\n"
            "Please extract the changes according to the specified schema."
        )

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_content},
        ]

        # Call OpenAI with Structured Outputs — auto-traced via langfuse.openai wrapper
        response = self.client.beta.chat.completions.parse(
            model="gpt-4o",
            messages=messages,
            response_format=ContractChangeOutput,
            temperature=0.0,
            name="extraction-gpt-4o",
        )

        parsed_output = response.choices[0].message.parsed

        if parsed_output is None:
            raise ValueError("Failed to parse the structured output from OpenAI.")

        # Update span output
        langfuse.update_current_span(output=parsed_output.model_dump())

        return parsed_output
